apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-02cv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-02cv@sha256:ab079d288cafd2de33b50b36cf292c26f93f6eaa5f509bb5b5ba82c0044809a7
        name: my-nodejs
        resources: {}
status: {}
